IF OBJECT_ID('GradeSubjectMapping') IS NULL
BEGIN
	CREATE TABLE GradeSubjectMapping
	(
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		GradeId INT NOT NULL DEFAULT 0,
		SubjectId INT NOT NULL DEFAULT 0,
		SectionId INT NULL,
		LabFee DECIMAL(18,2) NOT NULL DEFAULT 0,
		Deleted BIT NOT NULL DEFAULT 0,
		CreatedBy INT NOT NULL DEFAULT 0,
		CreatedOnUtc DATETIME NOT NULL,
		UpdatedBy INT NOT NULL DEFAULT 0,
		UpdatedOnUtc DATETIME NULL
	)
END